name: Deploy content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main
    paths:
      - '*/**'
      - '!**.md'
      - '!.github/**'
      - '.github/workflows/pages.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        
      - name: Install dependencies
        run: pip install pillow markdown

      - name: Unpack zips
        run: |
          shopt -s nullglob
          cd sets
          for file in *.zip; do
            unzip -u "$file"
          done

      - name: Make exporter zip
        run: |
          cd resources
          zip exporter.zip *.mse-export-template -r
          mv exporter.zip ..
        
      - name: Build
        run: python scripts/build_site.py
        
      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Add repo link
        run: echo '<meta http-equiv="refresh" content="0; url=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY">' >repo.html
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          # Upload entire repository
          path: '.'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5